-- MySQL Script generated by MySQL Workbench
-- Wed Jun 16 16:49:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crudwithviacepapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crudwithviacepapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crudwithviacepapi` DEFAULT CHARACTER SET utf8 ;
USE `crudwithviacepapi` ;

-- -----------------------------------------------------
-- Table `crudwithviacepapi`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crudwithviacepapi`.`endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(200) NOT NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(250) NULL,
  `cidade` VARCHAR(250) NULL,
  `uf` VARCHAR(250) NULL,
  `cep` VARCHAR(8) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crudwithviacepapi`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crudwithviacepapi`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `endereco_idEndereco`),
  INDEX `fk_cliente_endereco_idx` (`endereco_idEndereco` ASC),
  CONSTRAINT `fk_cliente_endereco`
    FOREIGN KEY (`endereco_idEndereco`)
    REFERENCES `crudwithviacepapi`.`endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
